# This is Assignment 11 - John Saia

## Requirement 3

In your own words, describe the commonalities and differences between NumPy arrays and Pandas series.

Numpy creates and allows manipulations of lists/arrays in an efficent fashion particularly numerical. Pandas is built on top of the Numpy library and enables better manipulation of dataframes type uses. Pandas aids in labeling, missing data values, grouping, and pivots. Numpy is thought more in terms of indicies.

## Requirement 4

In [1]:
# Create a Pandas series named bill_names with American currency bill
# denominations as indices (keys) and President last names as values. For
# example: 1 – Washington, 2 – Jefferson, etc.

import pandas as pd

bill_names = pd.Series(['Washington', 'Jeffeson', 'Hamilton', 'Lincoln', 'Jackson', 'Grant', 'Franklin'],
                       index=[1, 2, 3, 4, 5, 6, 7])

bill_names

1    Washington
2      Jeffeson
3      Hamilton
4       Lincoln
5       Jackson
6         Grant
7      Franklin
dtype: object

## Requirement 5

In [2]:
# Create a Pandas series-as-dictionary beverages_dict. Make the indices
# beverage names and comments about the beverage as values. For example:
# ‘Aquafina’: ‘This is my favorite bottled water!’. Demonstrate accessing:
# individual values via the keys

beverages_dict = pd.Series({'Dr. Pepper':'It has a cherry like sweet spiciness',
                            'Root Beer': 'It is smooth with a sweet vanilla taste',
                            'Mountain Dew': 'It has a citrus taste'})

print(beverages_dict['Dr. Pepper'])
print('\n')
print(beverages_dict['Mountain Dew'])
print('\n')

# multiple values via slicing

print(beverages_dict['Root Beer':])
print('\n')

print(beverages_dict['Dr. Pepper':'Mountain Dew'])

It has a cherry like sweet spiciness


It has a citrus taste


Root Beer       It is smooth with a sweet vanilla taste
Mountain Dew                      It has a citrus taste
dtype: object


Dr. Pepper         It has a cherry like sweet spiciness
Root Beer       It is smooth with a sweet vanilla taste
Mountain Dew                      It has a citrus taste
dtype: object


## Requirement 6

In [3]:
# Obtain the real city proper population data for the following cities:
# Chongquing, Shanghai, Tokyo, Moscow, Mexico City, London, & New York.
# Create a series-as-dictionary named population based on this information

population = pd.Series({'Chongquing': 32054159,
                        'Shanghai': 24870895,
                        'Tokyo': 13960000,
                        'Moscow': 13010112,
                        'Mexico City': 9209944,
                        'London': 8799800,
                        'New York': 8804190})

population

Chongquing     32054159
Shanghai       24870895
Tokyo          13960000
Moscow         13010112
Mexico City     9209944
London          8799800
New York        8804190
dtype: int64

## Requirement 7

In [4]:
# Create a Pandas series-as-dictionary named city_country with the cities in
# population and the countries for each city.

city_country = pd.Series({'Chongquing': 'China',
                          'Shanghai': 'China',
                          'Tokyo': 'Japan',
                          'Moscow': 'Russia',
                          'Mexico City': 'Mexico',
                          'London': 'United Kingdom',
                          'New York': 'United States'})

city_country

Chongquing              China
Shanghai                China
Tokyo                   Japan
Moscow                 Russia
Mexico City            Mexico
London         United Kingdom
New York        United States
dtype: object

## Requirement 8

In [5]:
# Create a Pandas dataframe object named city_dataframe from a dictionary
# of series objects using population and city_country. Show:

city_dataframe = pd.DataFrame({'Population': population,
                               'Country': city_country})

print(city_dataframe)
print('\n')

# the .index property

print(city_dataframe.index)
print('\n')

# the .columns property

print(city_dataframe.columns)
print('\n')

# the .keys() method

print(city_dataframe.keys())

             Population         Country
Chongquing     32054159           China
Shanghai       24870895           China
Tokyo          13960000           Japan
Moscow         13010112          Russia
Mexico City     9209944          Mexico
London          8799800  United Kingdom
New York        8804190   United States


Index(['Chongquing', 'Shanghai', 'Tokyo', 'Moscow', 'Mexico City', 'London',
       'New York'],
      dtype='object')


Index(['Population', 'Country'], dtype='object')


Index(['Population', 'Country'], dtype='object')


## Requirement 9

In [6]:
# Create a Pandas series object named my_pd_series from a collection of
# string keys and collection of numeric values of your choosing. Demonstrate:

my_pd_series = pd.Series({'hihihi':101010, 'byebyebye':202020, 'hello':404040})

print(my_pd_series)
print('\n')

# modifying a value based on key

my_pd_series['byebyebye'] = 303030

print(my_pd_series)
print('\n')

# slicing by explicit index

print(my_pd_series['byebyebye':'hello'])
print('\n')

# slicing by implicit integer index

print(my_pd_series[0:2])
print('\n')

# masking

print(my_pd_series[my_pd_series < 202020])
print('\n')

# fancy indexing

print(my_pd_series[['hihihi','hello']])
print('\n')

# loc[]

print(my_pd_series.loc['hello'])
print('\n')

# iloc[]

print(my_pd_series.iloc[1])

hihihi       101010
byebyebye    202020
hello        404040
dtype: int64


hihihi       101010
byebyebye    303030
hello        404040
dtype: int64


byebyebye    303030
hello        404040
dtype: int64


hihihi       101010
byebyebye    303030
dtype: int64


hihihi    101010
dtype: int64


hihihi    101010
hello     404040
dtype: int64


404040


303030


## Requirement 10

In [7]:
# Using city_dataframe, demonstrate:
# access column via dictionary-style indexing of the column name

print(city_dataframe['Country'])
print('\n')

# access column via column names that are strings

print(city_dataframe.Country)
print('\n')

# add a new column to the city_dataframe named altitude.

city_dataframe['altitude'] = [801, 13.12, 131, 512, 7319, 36, 33]

altitude = pd.Series({'Chongquing': 801,
                      'Shanghai': 13.12,
                      'Tokyo': 131,
                      'Moscow': 512,
                      'Mexico City': 7319,
                      'London': 36,
                      'New York': 33})

city_dataframe = pd.DataFrame({'Population': population,
                               'Country': city_country,
                               'Altitude': altitude})

print(city_dataframe)

Chongquing              China
Shanghai                China
Tokyo                   Japan
Moscow                 Russia
Mexico City            Mexico
London         United Kingdom
New York        United States
Name: Country, dtype: object


Chongquing              China
Shanghai                China
Tokyo                   Japan
Moscow                 Russia
Mexico City            Mexico
London         United Kingdom
New York        United States
Name: Country, dtype: object


             Population         Country  Altitude
Chongquing     32054159           China    801.00
Shanghai       24870895           China     13.12
Tokyo          13960000           Japan    131.00
Moscow         13010112          Russia    512.00
Mexico City     9209944          Mexico   7319.00
London          8799800  United Kingdom     36.00
New York        8804190   United States     33.00


## Requirement 11

In [8]:
# Create two Pandas series that when added using ‘+’ produce some NaN
# entries. Use the .add() method and a fill_value to replace the NaN entries

series1 = pd.Series({'a': 1, 'b': 2, 'c': 3})

series2 = pd.Series({'a': 2, 'd': 3, 'b': 4})

print(series1 + series2)

print(series1.add(series2, fill_value=0))



a    3.0
b    6.0
c    NaN
d    NaN
dtype: float64
a    3.0
b    6.0
c    3.0
d    3.0
dtype: float64


## Requirement 12

In [9]:
# Create two Pandas dataframes that when added using ‘+’ produce some
# NaN entries. Use the .add() method and a fill_value of the mean of one of
# the dataframes to replace the NaN entries.

import numpy as np

rng = np.random.RandomState(42)

df1 = pd.DataFrame(rng.randint(0, 15, (3, 3)),
                   columns=list('QTP'))

df2 = pd.DataFrame(rng.randint(0, 10, (4, 4)),
                   columns=list('QTPI'))

print(df1 + df2)

print(df2.add(df1, fill_value = 0))

    I     P     Q     T
0 NaN  18.0  15.0   5.0
1 NaN  14.0  18.0  13.0
2 NaN  10.0  14.0   9.0
3 NaN   NaN   NaN   NaN
     I     P     Q     T
0  7.0  18.0  15.0   5.0
1  7.0  14.0  18.0  13.0
2  1.0  10.0  14.0   9.0
3  4.0   1.0   7.0   5.0


## Requirement 13

In [10]:
# Create a two-dimensional NumPy array using:
# A = rng.randint(5, 10, size=(4, 4))
# Demonstrate: subtracting row 0 of A from A

A = rng.randint(5, 10, size=(4, 4))

print(A)
print(A-A[0])

[[5 8 6 9]
 [8 5 5 7]
 [7 6 8 8]
 [7 8 8 5]]
[[ 0  0  0  0]
 [ 3 -3 -1 -2]
 [ 2 -2  2 -1]
 [ 2  0  2 -4]]


## Requirement 14

In [11]:
# Create a Pandas dataframe using:
# df = pd.DataFrame(A, columns=list('QRST'))

df = pd.DataFrame(A, columns=list('QRST'))

print(df)
print('\n')

# Demonstrate: subtracting row 1 of df from df using df.iloc[1]

print(df - df.iloc[1])

   Q  R  S  T
0  5  8  6  9
1  8  5  5  7
2  7  6  8  8
3  7  8  8  5


   Q  R  S  T
0 -3  3  1  2
1  0  0  0  0
2 -1  1  3  1
3 -1  3  3 -2


## Requirement 15

Compare and contrast the two sentinel values Pandas uses to represent missing data.

None is a Python singleton object that is often used for missing data in Python code. It cannot be used in any arbitrary Numpy/Pandas array, but only in arrays with data type object. None being an object makes aggregations across array to generate errors. Nan, not a number, is the other missing data representation and is different. It is a special floating-point value recognized by all systems that use the standard IEEE floating-pint representation. Nan infects any other object it touches into nan, but the aggregations don't result in error. Python even has aggregations that will ignore nan values.

# Requirement 16

In [12]:
# Demonstrate the %timeit difference between operations using Python
# objects and Python integers

%timeit pd.Series(range(3), dtype=int)

%timeit pd.Series(range(3), dtype=object)

60.7 µs ± 832 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
46.3 µs ± 1.52 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## Requirement 17

In [13]:
# Create a Pandas series containing null data. Use .isnull() to identify the
# entries that are null.

nuls = pd.Series([1, 5, 6, np.nan, None])

nuls.isnull()

0    False
1    False
2    False
3     True
4     True
dtype: bool

## Requirement 18

In [14]:
# Create a Pandas dataframe containing null values. Demonstrate:

dfna = pd.DataFrame([[8, np.nan, 20, np.nan],
                     [20, 40, 65, np.nan],
                     [np.nan, np.nan, np.nan, np.nan]])

# drop all rows containing a null value

print(dfna.dropna())

print('\n')

# drop all columns containing a null value

print(dfna.dropna(axis='columns'))

print('\n')

# drop only rows that contain all null values

print(dfna.dropna(axis='rows', how='all'))

print('\n')

# drop only columns that contain all null values

print(dfna.dropna(axis='columns', how='all'))

print('\n')

# replacing null with 0

print(dfna.fillna(0))

print('\n')

# forward fill

print(dfna.fillna(method='ffill'))

print('\n')
                     
# backward fill 

print(dfna.fillna(method='bfill'))

Empty DataFrame
Columns: [0, 1, 2, 3]
Index: []


Empty DataFrame
Columns: []
Index: [0, 1, 2]


      0     1     2   3
0   8.0   NaN  20.0 NaN
1  20.0  40.0  65.0 NaN


      0     1     2
0   8.0   NaN  20.0
1  20.0  40.0  65.0
2   NaN   NaN   NaN


      0     1     2    3
0   8.0   0.0  20.0  0.0
1  20.0  40.0  65.0  0.0
2   0.0   0.0   0.0  0.0


      0     1     2   3
0   8.0   NaN  20.0 NaN
1  20.0  40.0  65.0 NaN
2  20.0  40.0  65.0 NaN


      0     1     2   3
0   8.0  40.0  20.0 NaN
1  20.0  40.0  65.0 NaN
2   NaN   NaN   NaN NaN


## Requirement 19

In [15]:
# Demonstrate Pandas MultiIndex techniques (can use book examples):
# .from_tuples()

index1 = [('Revenue', 2000), ('Revenue', 2010),
         ('Expenses', 2000), ('Expenses', 2010),
         ('Profit', 2000), ('Profit', 2010)]

amounts = [50000, 60000, 20000, 25000, 30000, 35000]

multii = pd.MultiIndex.from_tuples(index1)

print(multii)

financedf = pd.Series(amounts, index=multii)

print('\n')

# .reindex()

financedf2 = financedf.reindex(index1)

print(financedf2)

print('\n')

# .unstack()

financedf2 = financedf2.unstack()

print(financedf2)

print('\n')

# .stack()

print(financedf2.stack())

# indexing and slicing

print(financedf['Revenue'])

print('\n')

print(financedf[:, 2010])

print('\n')

print(financedf.loc[:])

print('\n')

print(financedf[financedf > 31000])

print('\n')

print(financedf[['Profit', 'Expenses']])

MultiIndex([( 'Revenue', 2000),
            ( 'Revenue', 2010),
            ('Expenses', 2000),
            ('Expenses', 2010),
            (  'Profit', 2000),
            (  'Profit', 2010)],
           )


Revenue   2000    50000
          2010    60000
Expenses  2000    20000
          2010    25000
Profit    2000    30000
          2010    35000
dtype: int64


           2000   2010
Expenses  20000  25000
Profit    30000  35000
Revenue   50000  60000


Expenses  2000    20000
          2010    25000
Profit    2000    30000
          2010    35000
Revenue   2000    50000
          2010    60000
dtype: int64
2000    50000
2010    60000
dtype: int64


Revenue     60000
Expenses    25000
Profit      35000
dtype: int64


Revenue   2000    50000
          2010    60000
Expenses  2000    20000
          2010    25000
Profit    2000    30000
          2010    35000
dtype: int64


Revenue  2000    50000
         2010    60000
Profit   2010    35000
dtype: int64


Profit    2000    30000
   

## Requirement 20

In [16]:
# Demonstrate concatenating two Pandas series. One series contains
# automobile data. The other series contains motorcycle data.

autoS = pd.Series(['Mustang', 'GTI', 'A4'], index=['Ford', 'VW', 'Audi'])

motoS = pd.Series(['Shine', 'R 18', 'Ninja H2R'], index=['Honda', 'BMW', 'Kawasaki'])

pd.concat([autoS, motoS])

Ford          Mustang
VW                GTI
Audi               A4
Honda           Shine
BMW              R 18
Kawasaki    Ninja H2R
dtype: object

## Requirement 21

In [17]:
# Demonstrate concatenating two Pandas dataframe using the .append() method.

dfa1 = pd.DataFrame({'A': [10, 20], 'B': [30, 40]})

dfa2 = pd.DataFrame({'A': [25, 201], 'B': [130, 40]})

display(dfa1, dfa2, dfa1.append(dfa2))

C:\Users\punxi\AppData\Local\Temp\ipykernel_7308\1552603308.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  display(dfa1, dfa2, dfa1.append(dfa2))


A   B
0  10  30
1  20  40

A    B
0   25  130
1  201   40

A    B
0   10   30
1   20   40
0   25  130
1  201   40

## Requirement 22

In [18]:
# Using Pandas dataframes, demonstrate the following joins:
# one-to-one

dfmer1 = pd.DataFrame({'employee': ['John', 'Steve', 'Sam', 'Jim'],
                       'group': ['Finance', 'Finance', 'HR', 'Retail']})

dfmer2 = pd.DataFrame({'employee': ['John', 'Steve', 'Kim', 'Jim'],
                        'hire_date': [2020, 2019, 2022, 2021]})

dfmer3 = pd.merge(dfmer1, dfmer2)

print(dfmer3)
print('\n')

# many-to-one

dfmer4 = pd.DataFrame({'group': ['Finance', 'HR', 'Retail'],
                       'supervisor': ['Jeremy', 'Tom', 'Michael']})

dfmer4 = pd.merge(dfmer1, dfmer4)

print(dfmer4)
print('\n')

# many-to-many

dfmer5 = pd.DataFrame({'group': ['Finance', 'Finance',
                                 'HR', 'HR', 'Retail', 'Retail'],
                       'skills': ['math', 'spreadsheets', 'organization', 'spreadsheets',
                                  'stocking', 'inventory']})

dfmer6 = pd.merge(dfmer1, dfmer5)

print(dfmer6)

  employee    group  hire_date
0     John  Finance       2020
1    Steve  Finance       2019
2      Jim   Retail       2021


  employee    group supervisor
0     John  Finance     Jeremy
1    Steve  Finance     Jeremy
2      Sam       HR        Tom
3      Jim   Retail    Michael


  employee    group        skills
0     John  Finance          math
1     John  Finance  spreadsheets
2    Steve  Finance          math
3    Steve  Finance  spreadsheets
4      Sam       HR  organization
5      Sam       HR  spreadsheets
6      Jim   Retail      stocking
7      Jim   Retail     inventory


## Requirement 23

In [19]:
# Using Pandas dataframes, demonstrate merge with the following keywords:
# on

dfmer7 = pd.merge(dfmer1, dfmer2, on='employee')

print(dfmer7)
print('\n')

# left_on and right_on

dfmer8 = pd.merge(dfmer1, dfmer3, left_on="employee", right_on="employee")

print(dfmer8)
print('\n')

# left_index and right_index

dfmer1a = dfmer1.set_index('employee')
dfmer2a = dfmer2.set_index('employee')

dfmer9 = pd.merge(dfmer1a, dfmer2a, left_index=True, right_index=True)

print(dfmer9)

  employee    group  hire_date
0     John  Finance       2020
1    Steve  Finance       2019
2      Jim   Retail       2021


  employee  group_x  group_y  hire_date
0     John  Finance  Finance       2020
1    Steve  Finance  Finance       2019
2      Jim   Retail   Retail       2021


            group  hire_date
employee                    
John      Finance       2020
Steve     Finance       2019
Jim        Retail       2021


## Requirment 24

I felt it was an overly thorough introduction to series, dataframes, and merge functionality. The creation of the dataframes and series took some time. I wasn't exposed to the MultiIndex object since I usually had data in the dataframe and used a groupby function to get it in a similar state. It was interesting. I liked the relational data join section.